apiVersion: v1
kind: Pod
metadata:
  name: emptydir-memory-pod
spec:
  containers:
  - image: centos
    name: client
    command: [ "sleep", "3600" ]
    volumeMounts:
    - mountPath: /data
      name: data
  volumes:
  - name: data
    emptyDir:
      medium: Memory
