kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-volume-static-block-pvc
spec:
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-volume-static-block
