apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-using-kubectl
spec:
  inputs:
    resources:
      - name: source
        type: git
      - name: image
        type: image
    params:
      - name: path
        type: string
        description: Path to the manifest to apply
      - name: yamlPathToImage
        type: string
        description:
          The path to the image to replace in the yaml manifest (arg to yq)
  steps:
    - name: replace-image
      image: mikefarah/yq
      command: ["yq"]
      args:
        - "w"
        - "-d1"
        - "-i"
        - "$(inputs.params.path)"
        - "$(inputs.params.yamlPathToImage)"
        - "$(inputs.resources.image.url)"
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(inputs.params.path)"

---

apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: go-cicd-pipeline
spec:
  resources:
    - name: source
      type: git
    - name: builtImage
      type: image
  params:
    - name: package
      type: string
      default: github.com
    - name: packages
      type: string
      default: ./...
    - name: testflags
      type: string
      default: -race -cover -v
  tasks:
    # - name: lint
    #   taskRef:
    #     name: golangci-lint
    #   params:
    #     - name: package
    #       value: $(params.package)
    #   resources:
    #     inputs:
    #       - name: source
    #         resource: source
    - name: test
      taskRef:
        name: golang-test
      params:
        - name: package
          value: $(params.package)
        - name: packages
          value: $(params.packages)
        - name: flags
          value: $(params.testflags)
      resources:
        inputs:
          - name: source
            resource: source
    - name: image
      taskRef:
        name: kaniko
      runAfter:
        - test
      resources:
        inputs:
          - name: source
            resource: source
        outputs:
          - name: image
            resource: builtImage
    - name: deploy
      taskRef:
        name: deploy-using-kubectl
      params:
        - name: path
          value: /workspace/source/auto_deploy.yaml
        - name: yamlPathToImage
          value: "spec.template.spec.containers[0].image"
      resources:
        inputs:
          - name: source
            resource: source
          - name: image
            resource: builtImage
            from:
              - image
