apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeline-run-role
rules:
- apiGroups:
  - ""
  - extensions
  resources:
  - deployments
  - configmaps
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-run-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipeline-run-role
subjects:
- kind: ServiceAccount
  name: pipeline-run-service
  namespace: cicd

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-run-service
  namespace: cicd
secrets:
  - name: regcred

