apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim3
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-volume-dynamic-file
