apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - image: centos
    name: client
    command: [ "sleep", "3600" ]
    volumeMounts:
    - mountPath: /data
      name: data
  volumes:
  - name: data
    hostPath:
      path: /tmp/test
      type: DirectoryOrCreate
