apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-volume-dynamic-block-pvc2
spec:
  storageClassName: local-volume-dynamic-block
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 8Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: local-volume-dynamic-block-pod2
  annotations:
    container.apparmor.security.beta.kubernetes.io/client: unconfined
spec:
  containers:
    - name: client
      image: centos
      imagePullPolicy: Never
      command: ["/bin/sh", "-c"]
      args: ["tail -f /dev/null"]
      securityContext:
        capabilities:
          add: ["SYS_ADMIN"]
      volumeDevices:
        - name: device
          devicePath: /dev/xvde
  volumes:
    - name: device
      persistentVolumeClaim:
        claimName: local-volume-dynamic-block-pvc2
