apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-volume-dynamic-block-pvc
spec:
  storageClassName: local-volume-dynamic-block
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
