apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-volume-dynamic-block-admin
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-storage:provisioner-pv-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: local-volume-dynamic-block-admin
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:persistent-volume-provisioner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-storage:provisioner-node-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node
subjects:
- kind: ServiceAccount
  name: local-volume-dynamic-block-admin
  namespace: default
