apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-volume-dynamic-file-pvc2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: local-volume-dynamic-file
---
kind: Pod
apiVersion: v1
metadata:
  name: local-volume-dynamic-file-pod2
spec:
  containers:
    - name: client
      image: ikubernetes/myapp:v3
      volumeMounts:
      - mountPath: "/data"
        name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: local-volume-dynamic-file-pvc2
