apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-volume-dynamic-file-pvc
spec:
  storageClassName: local-volume-dynamic-file
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
