apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-static-file
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-volume-static-file
  local:
    path: /mnt/local/ycy
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s02-03
