apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-volume-static-file-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-volume-static-file
